- .gitignore
- bytelatent/args.py
- bytelatent/data/file_util.py
- bytelatent/data/iterators/arrow_iterator.py
- bytelatent/logger.py
- requirements.txt
- setup/download_prepare_hf_data.py
Summary:
For compatibility with either local/nfs or S3 datasets, swap to fsspec.
Add a tool to compare local and remote filesystems
Test Plan:
- Ran regular train script
- Ran with config with data in S3
> Replace regular filesystem calls with fsspec + add s3 support

- bytelatent/data/patcher.py
- bytelatent/preprocess/preprocess_entropies.py
- requirements.txt
> Update preprocess_entropies script to blt inference + add fsspec support

- bytelatent/data/file_util.py
> Update file check script to check sizes

- bytelatent/args.py
> Use load_async flag to not start MP iterator

- apps/main/lingua_train.py
- bytelatent/args.py
- bytelatent/checkpoint.py
- bytelatent/configs/debug.yaml
- bytelatent/configs/entropy_model.yaml
- bytelatent/data/data_types.py
- bytelatent/data/iterators/multiprocess_iterator.py
- bytelatent/eval.py
- bytelatent/generate.py
- bytelatent/train.py
It also batches in a first set of changes for fixing eval code
Summary:
Test Plan:
> This includes fixes that make checkpointing and reloading work correctly.

- bytelatent/metrics.py
> Fix wandb logging

- bytelatent/base_transformer.py
- bytelatent/model/blt.py
- bytelatent/model/local_models.py
- bytelatent/train.py
Add flag to do rope outer product in fp32
> Add rope fp32

- bytelatent/base_transformer.py
- bytelatent/distributed.py
- bytelatent/model/blt.py
- bytelatent/model/latent_transformer.py
- bytelatent/model/local_models.py
- bytelatent/transformer.py
1. Fix init order and std_devs
2. Remove unnecessary modules like layers and embeddings in the main BLT module
Test
1. Reproduces loss on 400m chinchilla optimal model
> Fix init and repro

- bytelatent/model/local_models.py
Remove unused norm and tok_embeddings in local_encoder and local_decoder respectively
> fix save and reload model state

- bytelatent/train.py
make sure max_encoder_seq_length matches in both data and model args
> make sure max_encoder_seq_length matches

- bytelatent/transformer.py
Disable reshard after forward, since we don't need it for now
> Disable raf

- bytelatent/base_transformer.py
- bytelatent/model/latent_transformer.py
- bytelatent/model/local_models.py
- bytelatent/transformer.py
Apex RMSNorm is more memory efficient, use it if available
> using apex rmsnorm

- bytelatent/base_transformer.py
- bytelatent/model/latent_transformer.py
- bytelatent/model/local_models.py
- bytelatent/transformer.py
> Make apex logs less noisy

- bytelatent/data/iterators/arrow_iterator.py
> Correctly reset batch iterator at each arrow create_iter call.

- bytelatent/args.py
- bytelatent/data/iterators/multiprocess_iterator.py
- bytelatent/train.py
Summary:
Test Plan:
***
More verbose multiprocess logging, fix get_state_and_recycle
Summary:
Test Plan:
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/facebookresearch/blt/pull/73).
* #77
* #75
* __->__ #73
> Add approximate state persistence

- bytelatent/data/iterators/multiprocess_iterator.py
> Let process start before yielding preloaded prefetch buffer, avoid needlessly losing buffer in edge cases

- bytelatent/args.py
- bytelatent/data/iterators/arrow_iterator.py
- bytelatent/data/iterators/sequence_iterator.py
- bytelatent/iterate_data.py
- bytelatent/train.py
> Reduce per file resources arrow uses

- bytelatent/config_parser.py
Tested with
```
config: prev_config
sources:
new_source_1: 3
new_source_2: 5
```
> When merging configs, do not merge data sources

- bytelatent/checkpoint.py
Tested using:
```
python -m bytelatent.checkpoint consolidate <path>
```
> Add way to call consolidate

- bytelatent/args.py
- bytelatent/data/iterators/packing_iterator.py
- bytelatent/eval.py
Summary:
Test Plan:
Run
```
python -m bytelatent.eval config=../internal-blt/configs/eval_blt.yaml validation.max_n_docs=null
python -m bytelatent.eval config=../internal-blt/configs/eval_entropy.yaml validation.max_n_docs=null
```
> Update ppl evals to work with blt model, in addition to entropy model

- bytelatent/args.py
- bytelatent/data/patcher.py
- bytelatent/distributed.py
- bytelatent/eval.py
- bytelatent/generate.py
- bytelatent/generate_blt.py
Summary:
Create a script for simple generation from BLT
Test Plan:
```
python -m bytelatent.generate_blt config=../internal-blt/configs/eval_blt.yaml
```
> Get generation working for BLT

- bytelatent/distributed.py
- bytelatent/generate.py
generate_nocache in generate_blt uses dist_sum. Adding dist_init when loading model, so that generate doesnt fail
> Init distributed when loading model

- .gitignore
- README.md
- bytelatent/data/patcher.py
- bytelatent/eval.py
- bytelatent/generate.py
- demo.py
- download_blt_weights.py
Summary:
Add code to download weights and demo code for running model.
Weights at:
- https://huggingface.co/collections/facebook/blt-6801263d4ac1704702a192a6
- https://huggingface.co/facebook/blt
- https://huggingface.co/facebook/blt-1b
- https://huggingface.co/facebook/blt-7b
Test Plan:
> Open source weights!

- README.md
- bytelatent/base_transformer.py
- bytelatent/data/patcher.py
- bytelatent/entropy_model.py
- bytelatent/hf.py
- bytelatent/model/blt.py
- bytelatent/preprocess/preprocess_entropies.py
- bytelatent/test_entropy_model.py
- bytelatent/transformer.py
> Improve HF compatibility

- README.md
- pyproject.toml
- requirements.txt
- setup/create_env.sh
- uv.lock
> Fix and improve env build options

- bytelatent/data/file_util.py
- bytelatent/data/iterators/arrow_iterator.py
- pyproject.toml
- uv.lock
> Tune retry params as temporary fix for excessive file listing

- README.md
- bytelatent/config_parser.py
- bytelatent/stool.py
- demo.py
- pyproject.toml
- uv.lock
> Run black/isort to fix linting
