- setup.py
This PR implements a `setup.py` file, such that BLT can be installed like a module, and integrated into other projects.
Pretty straightforward. You can see how I'm doing that [here](https://github.com/0-5788719150923125/praxis/blob/main/praxis/modules/encoder.py), if you like.
> Package `bytelatent` as a module

- bytelatent/base_transformer.py
- bytelatent/distributed.py
Currently, I am dealing with two different failure states, when trying to import and use `bytelatent` as a module. The first is an incompatibility with Python 3.13:
```
RuntimeError: Dynamo is not supported on Python 3.13+
```
The second is that my GPU does not support FlexAttention, at all. And thus, `torch.compile(flex_attention)` will always fail - preventing me from using this lib.
This PR is a simple fix to both problems. If FlexAttention fails to compile, or if it is otherwise unavailable for any reason - this code will allow us to fallback to a simpler implementation.
> allow flex-attention to be disabled

- bytelatent/args.py
- bytelatent/base_transformer.py
- bytelatent/configs/debug.yaml
- bytelatent/data/iterators/test_arrow_iterator.py
- bytelatent/distributed.py
- bytelatent/entropy_model.py
- bytelatent/model/blt.py
- bytelatent/model/latent_transformer.py
- bytelatent/model/local_models.py
- bytelatent/model/utils.py
- bytelatent/preprocess/fsspec_target.py
- bytelatent/test_blt.py
- bytelatent/test_entropy_model.py
- bytelatent/train.py
- bytelatent/transformer.py
Summary:
- Refactor local model configs to be separate and clearer
- Add attention arguments and correct which attention is used in local models
- Preparation for being able to have an entropy train script
- Fix failing unit tests
Test Plan:
> [WIP] Changes for training entropy model and correcting attention in local models

- bytelatent/data/patcher.py
- bytelatent/model/local_models.py
- bytelatent/model/utils.py
- bytelatent/preprocess/preprocess_entropies.py
This is a followup to the comment [made here](https://github.com/facebookresearch/blt/pull/25#issuecomment-2599152444).
I want to load and train an entropy model alongside of the latent model - rather than loading it from checkpoint. The current code does not support this, so I added an additional `PatcherArgs` attribute, called `entropy_model`. Here, you can pass a Pytorch module directly, instead of a checkpoint path.
I also removed a `self.output_proj` variable, because it crashes when using entropy patching. The `entropy_model_checkpoint_dir` attribute does not exist on `LocalModelArgs`. Regardless, this variable is unused - and probably not necessary?
Finally, I removed a logger warning that was extremely spammy. We are already gating this warning with the `BLT_SUPPRESS_ATTN_ERROR` …
> Fix realtime entropy patching

- bytelatent/norms.py
- bytelatent/train.py
Summary:
With >1 GPU, but only 1 node, all reduces fail when inputs are not bf16. This uses a modified copy of torch's grad norm to avoid failures
Test Plan:
- Run unit tests:
- Run single gpu training: `python -m bytelatent.train config=internal/configs/s3_debug.yaml eval=null checkpoint.dump.every=100`
- Run 1 node, multi-gpu training `torchrun --nproc-per-node 8 -m bytelatent.train config=internal/configs/s3_debug.yaml eval=null checkpoint.dump.every=100`
> Fix distributed all reduce grad norm

- bytelatent/args.py
- bytelatent/data/iterators/arrow_iterator.py
- bytelatent/preprocess/preprocess_entropies.py
- bytelatent/stool.py
Summary:
Currently, arrow iterator can only read arrow files. However, the pyarrow library can read
other formats, including jsonlines. This allows the same ArrowIterator to read from jsonlines,
so we can read from the original source data, and simply omit the entropy column when doing so
Test Plan:
Run train script until dataloader starts
> Allow ArrowIterator to read from json

- .gitignore
- bytelatent/distributed.py
- bytelatent/metrics.py
- bytelatent/train.py
> Add bpb and n_bytes to metric logging

- README.md
Changed "your can activate the environment" to "you can activate the environment" for clarity.
> fix(README): correct typo in quickstart instructions

- .gitignore
- bytelatent/args.py
- bytelatent/data/iterators/abstract_iterator.py
- bytelatent/data/iterators/arrow_iterator.py
- bytelatent/data/iterators/dev_iterators.py
- bytelatent/data/iterators/limit_iterator.py
- bytelatent/data/iterators/looping_iterator.py
- bytelatent/data/iterators/multiprocess_iterator.py
- bytelatent/data/iterators/packing_iterator.py
- bytelatent/data/iterators/preprocess_iterator.py
- bytelatent/data/iterators/sampling_iterator.py
- bytelatent/data/iterators/sequence_iterator.py
- bytelatent/data/iterators/test_arrow_iterator.py
- bytelatent/data/iterators/test_iters.py
- bytelatent/data/iterators/test_limit_iterator.py
- fixtures/test_docs.jsonl
- Create a common class to use in all inheritance for states
- Add a limit iterator that we can use in evals
- Modify ArrowFileIterator behavior to not do arrow path inference if file_format='json'
- Make EvalArgs valid
- Move testing iterators to a common directory to allow usage in multiple test files
- Make it so that SequenceIterator can take a None rng_state, to disable all rng ops (for eval mainly)
Test Plan:
- `pytest bytelatent`
- `python -m bytelatent.train config=../internal-blt/configs/entropy_model.yaml logging.wandb=null eval=null`
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/facebookresearch/blt/pull/63).
* #65
* __->__ #63
> Update iterator inheritance, pass file format args, limit iterator

- bytelatent/base_transformer.py
- bytelatent/transformer.py
Initialize rope_embeddings in init_weights, for the entropy model
> Initialize rope embeddings properly for the entropy model

- bytelatent/data/iterators/packing_iterator.py
- bytelatent/data/iterators/test_packing_iterator.py
This commit does/fixes the following:
1. Adds unit tests for byte and patch packing to ensure it works correctly
2. Fixes a bug where for batches that end up with <max_length number of bytes (e.g., short patches), the mask was including elements that had value pad_id. This fixes the mask by setting it to be !=pad_id, if its not specified.
3. Correctly handles the last batch, where previously it would crash. This didn't affect training since we had enough data and/or looped iterators, but for evaluation perplexity, it comes up if we validation on an entire file.
4. Correctly forward the mask if it exists for byte packing
Test Plan:
```
pytest bytelatent/
```
Testing these changes more thoroughly in a stacked PR that fixes evals
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with …
> Pass mask in packing_iterator, correctly handle last batch, fix masking

- bytelatent/stool.py
> Fix rsync to not preserve original permissions, instead use destination

- bytelatent/args.py
- bytelatent/distributed.py
- bytelatent/eval.py
- bytelatent/generate.py
- bytelatent/metrics.py
- bytelatent/train.py
- PPL/validation: Works now and uses multi-gpu. For some reason 1 GPU differs from multi-GPU, can debug in a followup PR
- Generation evals likely work, but are very slow, so disabled for now
Test Plan:
```
torchrun --nproc-per-node 8 -m bytelatent.eval config=../internal-blt/configs/eval.yaml
```
> Get evals working again.

- bytelatent/data/patcher.py
- bytelatent/entropy_model.py
1. Model args for entropy model are under the "entropy_model" key
2. model is under the "model" key in the state_dict for entropy_model
3. we might use other tokenizers, so removing the hardcoded check for 260
> Some fixes for entropy model predictions

- bytelatent/model/local_models.py
When training the BLT model, I encountered a runtime error caused by an in-place operation on tensor views.
The problem arises in `local_models.py` where the following in-place addition is performed.
```python  
patch_embeds += patch_embeds_cross
return patch_embeds 
```
```
[rank0]: Traceback (most recent call last):
[rank0]: File "<frozen runpy>", line 198, in _run_module_as_main
[rank0]: File "<frozen runpy>", line 88, in _run_code
[rank0]: File "/mnt/storage1/geranium/blt/bytelatent/train.py", line 812, in <module>
[rank0]: main()
[rank0]: File "/mnt/storage1/geranium/blt/bytelatent/train.py", line 808, in main
[rank0]: train(train_args)
[rank0]: File "/mnt/storage1/geranium/blt/bytelatent/train.py", line 486, in train
[rank0]: loss.backward()
[rank0]: File …
```
> Fix RuntimeError in Cross Attention Using Out-Of-Place Addition 

- bytelatent/distributed.py
7b models were trained with full AC, so removing these
> remove selective activation checkpointing

- bytelatent/args.py
- bytelatent/eval.py
Eval was not ignoring pad when computing cross entropy.
Also added a way to test eval by restricting the max_n_batches
> Fix eval mask

- bytelatent/data/iterators/arrow_iterator.py
Crashes when file_format == json, complains about sample_id being int. This fixes it
> Cast int sample id to str

- bytelatent/model/blt.py
This PR improves the integration with the 🤗 hub, by making the main class inherit from the [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/en/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) class.
Benefits:
- weights are serialized in [safetensors](https://github.com/huggingface/safetensors) format, instead of pickle
- download stats work
- the class automatically inhertis the `from_pretrained`, `save_pretrained` and `push_to_hub` methods.
Here's a demo notebook: https://colab.research.google.com/drive/1yJ252Fa9kY0A_43JWBDHnjREqht12nB5?usp=sharing.
It would be great if you could try this out, and overwrite the weights of the model repository with the updated ones.
> Improve HF integration

- bytelatent/config_parser.py
- bytelatent/stool.py
- bytelatent/templates/stool_template.sh.jinja
- pyproject.toml
- uv.lock
Summary:
Modify stool so that:
- It uses jinja2 for better templating
- Add args to allow force non-interactive overrides
- Add config_parser argument to allow instantiation of pydantic class when some defaults don't exist and use it in stool, to allow the rest of the configuration parser to work.
Test Plan:
```
uv run python -m bytelatent.stool config=/storage/home/par/code/internal-blt/configs/par/stool/run_blt_1b_aws.yaml
uv run python -m bytelatent.train config=../internal-blt/configs/par/train/aws/blt_1b_dclm_aws.yaml dump_dir=/checkpoint/comem/par/scratch/debug data.batch_size=2
```
> Upgrade stool

- README.md
- demo.py
- download_blt_weights.py
Summary:
Test Plan:
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/facebookresearch/blt/pull/116).
* #117
* __->__ #116
> Fix demo.py
